### ISSUE TITLE
Clinicaltrials_download temp directory not clearing

### ISSUE THREAD

**Issue by becca123** [sachsmc/rclinicaltrials#11]
When I used clinicaltrials_download I have found that that the tempfile() directory is not being cleared each time clinicalstrials_download is run using a query. This means that the next time the function is used it will download the new .xml files into the tempfile() directory but the results that are saved in the data.frame are a mix of the previous searches and current search. This is because the data.frame is calling a certain number of .xml files and the files are ordered by trial id. In the folder there are many more .xml files because all the .xml from previous searches are being saved. 

This can be fixed by adding  the following line before using the function clinicaltrials_download

**unlink(paste0(tempdir(), "\\*.xml"))**   

Example

drug_data <- clinicaltrials_download(query = "gemcitabine", tframe = NULL, count = NULL,
include_results = FALSE, include_textblocks =FALSE)

drug_data1 <- clinicaltrials_download(query ="Abiraterone",, tframe = NULL, count = NULL,
include_results = FALSE, include_textblocks =FALSE)

drug_data will contain 2040 results. 
drug_data1 will contain 193 results, some of those will be from the search on gemcitabine.

**Comment by sachsmc** [comment]
Thanks for the report, will push a fix momentarily.
