### ISSUE TITLE
Query results not matching direct pull from clinicaltrials.gov

### ISSUE THREAD

**Issue by deathinvenice** [sachsmc/rclinicaltrials#13]
Hello,

Im trying to use your R package to interrogate the API at clinicaltrials.gov for studies on glioblastoma.

When I directly query clinicaltrials.gov using conditions = glioblastoma, interventions=drug, phase = 3 & 4, and location terms = USA, I get 30 hits.

When I use this package, with this parameterization 
gbm <- clinicaltrials_search(query=c('cond=glioblastoma','phase=3+4','intr=drug','locn=USA'))
I get 15 hits.

Am I missing something obvious?

Regards

**Comment by sachsmc** [comment]
Hi,

Yes, the trial phase is coded as an offset. So to search for phase 3 and 4, the website codes this as phase 2 and 3. (Phase 0 is coded as 4, don't ask me why). Also the search function restricts to 20 results by default, set it to NULL to get all the results. This will get you the 30 trials you expect: 

    gbm <- clinicaltrials_search(query=c('cond=glioblastoma','phase=2+3','intr=drug','locn=USA'), count = NULL)
