### ISSUE TITLE
Searching using key value pairs is returning all trials

### ISSUE THREAD

**Issue by UiowaAdam** [sachsmc/rclinicaltrials#22]
Hello, I am new to R and Rclinicaltrials. I am attempting to use multiple search terms but it appears the terms are not being read or I am not using the correct syntax.

I am attempting to pull trials for Crohn's Disease and numerous drugs. 

clinicaltrials_count(query = "crohn") accurately returns 1393. Similarly clinicaltrials_count(term = "ozanimod") accurately returns 19. 

However, clinicaltrials_count(query = c(cond = "crohn", term = "ozanimod")) returns 313471. There are currently 6 trials with these criteria.

I have attempted variations of the vector but each results in a count of 313471. 

Please let me know if there is something different I can try.

Thanks,
UIowaAdam

**Comment by sachsmc** [comment]
The correct syntax is: 

    clinicaltrials_count(query = c("cond=crohn", "term=ozanimod"))


or

    clinicaltrials_count(query = list(cond="crohn", term="ozanimod"))
